### ISSUE TITLE
Code Coverage just stopped working.  Everything reports 0%

### ISSUE THREAD

**Issue by ecconner** [FortuneN/FineCodeCoverage#154] opened 2021-06-14 20:54 UTC
### Installed product versions
- Visual Studio: [example 2019 Community]
- This extension: [example 1.1.141]

### Description
Stopped working altogether.  I installed it about 3 weeks ago and it worked great out of the box.  I didn't change anything that I know of and it just stopped working.  Everything reports 0%.  I tried uninstalling the extension and reinstalling the extension but that did not make a difference

### Steps to recreate
1.  Just stopped working.  The most I know is that I shutdown the computer.  It was working fine.

### Current behavior
Reporting no coverage when running tests from test explorer.

### Expected behavior
Reporting coverage after running tests.

### Side Notes
- no side notes

**Comment by tonyhallett** [comment] 2021-06-14 21:20
Can you post the output from VS Output window, FCC pane.  

if you are using an sdk project then you should set up for coverlet collector

**Comment by ecconner** [comment] 2021-06-15 02:16
**FCC OUTPUT**


Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (StateMarshallService.UnitTest)

Fine Code Coverage : Coverlet Run (StateMarshallService.UnitTest) Arguments 
"C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\StateMarshallService.UnitTest.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\StateMarshallService.UnitTest.coverage.xml"
--targetargs "test  ""C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\StateMarshallService.UnitTest.dll"" --nologo --blame  --results-directory ""C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"" --diag ""C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (StateMarshallService.UnitTest)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.

Calculating coverage result...
  Generating report 'C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\StateMarshallService.UnitTest.coverage.xml'
+-------------------------------+------+--------+--------+
| Module                        | Line | Branch | Method |
+-------------------------------+------+--------+--------+
| Config                        | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| Core                          | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| DOM                           | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| GRPC.Mobile.Client            | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| GRPC.Mobile.Library           | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| GRPCClient                    | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| GRPCLibrary                   | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| Modbus                        | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| Protos                        | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| StateMarshallService          | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| StateMarshallService.UnitTest | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| TestHost                      | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| UnitTestBase                  | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| Utility                       | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+
| Proxy                         | 0%   | 0%     | 0%     |
+-------------------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 0%     | 0%     |
+---------+------+--------+--------+

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\StateMarshallService.UnitTest.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-06-14T16:48:28: Arguments
2021-06-14T16:48:28:  -targetdir:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output
2021-06-14T16:48:28:  -reports:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\StateMarshallService.UnitTest.coverage.xml
2021-06-14T16:48:28:  -reporttypes:Cobertura
2021-06-14T16:48:30: Writing report file 'C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-06-14T16:48:30: Report generation took 2.2 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:c:\users\...\appdata\local\microsoft\visualstudio\16.0_0d535431\extensions\v0qpxjpx.azh\ReportGeneratorPlugins.dll"
"-reporttypes:FccLight"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-06-14T16:48:30: Arguments
2021-06-14T16:48:30:  -targetdir:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output
2021-06-14T16:48:30:  -reports:C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-06-14T16:48:30:  -plugins:c:\users\...\appdata\local\microsoft\visualstudio\16.0_0d535431\extensions\v0qpxjpx.azh\ReportGeneratorPlugins.dll
2021-06-14T16:48:30:  -reporttypes:FccLight
2021-06-14T16:48:32: Writing report file 'C:\Users\...\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\index.html'
2021-06-14T16:48:32: Report generation took 2.0 seconds

Fine Code Coverage : ================================== DONE ==================================

**Comment by tonyhallett** [comment] 2021-06-15 07:51
When you say that it has stopped working, has it stopped working in a solution that previously worked or is it a different solution ?

What version of the package below do you have installed ?
`<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />`

FCC advises that you use the coverlet collector driver by adding the UseDataCollector element to each project file
`
<PropertyGroup>
	<UseDataCollector/>
</PropertyGroup>
`

**Comment by ecconner** [comment] 2021-06-15 10:58
Yes.  I installed the extension.  And it worked right out of the box on the solution i was working on.

I have v 16.10.0 of the SDK installed.

I can do that last step, but would prefer not to.  Its just code coverage, I would rather keep my project files agnostic to the fact that I have a code coverage tool.  Doesn't seem necessary.

**Comment by tonyhallett** [comment] 2021-06-15 12:20
FCC has not changed since you installed it so is there anything that you could have done that could be causing 
"An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified."

What test adapter are you specifying in your project file ?
What versions of .NET Sdk do you have installed ?

Are your tests running normally ?

> I can do that last step, but would prefer not to. Its just code coverage, I would rather keep my project files agnostic to the fact that I have a code coverage tool. Doesn't seem necessary.

It may not be necessary to use the coverlet collector but you are advised to use it for good reason.  

> Coverlet has different "drivers". Fine Code Coverage has in the past only used the coverlet console driver. This has some issues associated with it. If you encounter 0% coverage or inconsistent coverage it is now possible to switch to the Data Collector driver. This is the better driver but cannot be used for all projects.

> Fine Code Coverage will use the Data Collector driver under two circumstances :
You are testing with runsettings that contains the coverlet collector ( and not disabled)
You set the UseDataCollector project property

The issue that you are encountering probably will occur with that driver too.

**Comment by ecconner** [comment] 2021-06-15 16:08
Tests are running normally and passing.  Using MSTest. and Running them from VS TestExplorer
Using .Net 5.0.103
Some of these projects are running on .Net Standard 2.0 and .Net Core 3.1

What I don't understand is how it just stopped working because it was working great up till this week.  Is there a cache or config files somewhere in my local app data that i can delete.  I just wonder if something got set that shouldn't be and its preventing what was working form happening now.

**Comment by tonyhallett** [comment] 2021-06-15 16:44
Have you cleaned the solution ?

You could delete the fine code coverage folder in appdata, uninstall fine code coverage and reinstall although I doubt that is the issue.
`C:\Users\yourname\AppData\Local\FineCodeCoverage\`

You could also then delete from the bin/Debug/netcoreapp3.1etc/fine-code-coverage for each of the test projects.

Perhaps you can create a new minimal solution with a single test project to see if that works ok.

**Comment by tonyhallett** [comment] 2021-06-15 16:58
If you give me access to your project I will have a look

**Comment by Sergey1209** [comment] 2021-07-19 12:35
I experience the same: it stopped working around the same time. Could it be related to VS version?

**Comment by Sergey1209** [comment] 2021-07-19 12:35
Here is my log:
`Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (MessageHandlersCommon.Tests)

Fine Code Coverage : OpenCover Run (MessageHandlersCommon.Tests) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path32 
 "-target:C:\Users\Siarhei_Machel\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" 
 "-excludebyfile:**/Migrations/*" 
 "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" 
 "-targetargs:\"D:\Reuters\GIT\Development\MessageHandlers\MessageHandlersCommon.Tests\bin\Debug\fine-code-coverage\build-output\MessageHandlersCommon.Tests.dll\" " 
 "-output:D:\Reuters\GIT\Development\MessageHandlers\MessageHandlersCommon.Tests\bin\Debug\fine-code-coverage\coverage-tool-output\MessageHandlersCommon.Tests.coverage.xml"

Fine Code Coverage : Run Coverage Tool (MessageHandlersCommon.Tests) Failed
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CliWrap.Internal.ProcessEx.Start()
   at CliWrap.Command.<ExecuteAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CliWrap.Internal.Extensions.AsyncExtensions.<Select>d__0`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Core.Utilities.ProcessUtil.<ExecuteAsync>d__4.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Utilities\ProcessUtil.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at FineCodeCoverage.Engine.OpenCover.OpenCoverUtil.<RunOpenCoverAsync>d__11.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\OpenCover\OpenCoverUtil.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<StepAsync>d__62.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 343

Fine Code Coverage : ================================== DONE ==================================
`

**Comment by tonyhallett** [comment] 2021-11-14 14:42
Closing as I very much doubt that this is an issue with FCC.
If @ecconner enters in to a dialog then will reopen and try to ascertain the cause of the problem.

**Closed by tonyhallett** 2021-11-14 14:42 UTC
Labels: waiting for feedback
