### ISSUE TITLE
Extension stop working with 1.1.88 update

### ISSUE THREAD

**Issue by AsierVillanueva** [FortuneN/FineCodeCoverage#82] opened 2021-02-08 17:15 UTC
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2019 (version 16.8.4)
- This extension: 1.1.88

### Description
After last update the extension stop working. After running test in the build output window appears "Fine Code Coverage : ================ START ====================", but nothing else happens. No more messages and the Fine Code Coverage window stays empty.

Before this update the extension worked fine with same projects.

I have uninstalled the extension and installed 1.1.63 version, and has worked again. But if I update to the last version stop working.

**Comment by mmbatha** [comment] 2021-02-09 05:23
The same is true for Visual Studio Professional 2019 (version 16.8.4)

Also uninstalled version 1.1.88 in favour of 1.1.63 but the extension auto-updated before I ran the tests that had previously run.

**Comment by tonyhallett** [comment] 2021-02-09 10:29
@Pildoras @mmbatha My apologies the code does not work for .NET Framework projects.  Will correct shortly

**Comment by tonyhallett** [comment] 2021-02-09 11:08
@Pildoras @mmbatha I think the problem was due to visual studio api unkindly throwing NotImplementedException for dte Project.FullName for unloaded projects.

Please can you confirm that this is indeed the cause of the faulty behaviour.
https://ci.appveyor.com/api/buildjobs/i6v8mob8yuybbeh7/artifacts/FineCodeCoverage.vsix

**Comment by AsierVillanueva** [comment] 2021-02-09 12:23
@tonyhallett No. With this version (1.1.93) still not working.

![image](https://user-images.githubusercontent.com/13245640/107362926-b5793880-6ad9-11eb-911a-848486b30f9a.png)

**Comment by tonyhallett** [comment] 2021-02-09 12:34
@AsierVillanueva 
Ok thanks.  Could you give me some information on the projects in your solution.

**Comment by tonyhallett** [comment] 2021-02-09 13:08
@AsierVillanueva Does your test project reference a project that is unloaded ?

**Comment by tonyhallett** [comment] 2021-02-09 13:18
@AsierVillanueva Ignore that last comment I think I know the problem

**Comment by draxtor** [comment] 2021-02-09 13:28
@AsierVillanueva  how did you obtain 1.1.63 version? I can only download 1.1.88 & 1.1.94 and they're both not working with my projects.

**Comment by AsierVillanueva** [comment] 2021-02-09 13:32
@draxtor I downloaded it when I installed the extension a month ago.

**Comment by tonyhallett** [comment] 2021-02-09 13:34
@draxtor Give me a couple of minutes and I will see if I can find a link

**Comment by tonyhallett** [comment] 2021-02-09 13:46
@draxtor https://ci.appveyor.com/api/buildjobs/qyl7ibeackrettgv/artifacts/FineCodeCoverage.vsix  this is 1.1.62

**Comment by tonyhallett** [comment] 2021-02-09 14:23
@AsierVillanueva Any chance you could provide a repro ? The code looks sound.  If I could debug through I could resolve it quicker.

**Comment by AsierVillanueva** [comment] 2021-02-09 14:53
@tonyhallett 
I just have tried with a Solution with a Class Library Project and the extension works fine.
The three solutions it doesn't work on have an ASP.NET Core project. May be related?

**Comment by tonyhallett** [comment] 2021-02-09 14:55
@AsierVillanueva Thanks.  I will try on an ASP.NET Core project.  Thanks

**Comment by mmbatha** [comment] 2021-02-09 15:02
@tonyhallett The projects I tried to use the extension in, are .Net Core 2.1

**Comment by tonyhallett** [comment] 2021-02-09 15:03
@AsierVillanueva @mmbatha  What are the project types for all the projects in the solution ?

**Comment by tonyhallett** [comment] 2021-02-09 15:11
@AsierVillanueva @mmbatha Are the projects within a solution ?

**Comment by AsierVillanueva** [comment] 2021-02-09 15:13
@tonyhallett 
I've tried it on four solutions:

Solution 1 projects (in this works fine):
.Net Standard 2.0 Class library
.Net Core 3.1 Console App
.Net Core 3.1 Test project with XUnit

Solution 2 projects:
9 .Net Core 3.1 Class Library projects
1 ASP .Net Core 3.1 project
2 .Net Core 3.1 Test projects with XUnit

Solution 3 projects:
4 .Net Core 3.1 Class Library projects
6 .Net Standard 2.0 Class Library projects
1 ASP .Net Core 3.1 project
2 .Net Core 3.1 Test projects with XUnit

Solution 4 projects:
5 .Net Core 3.1 Class Library Projects
1 .Net Core 3.1 Console project
1 ASP .Net Core 3.1 project
1 .Net Core 3.1 Test project with XUnit

**Comment by tonyhallett** [comment] 2021-02-09 15:22
@AsierVillanueva For Solution 3 can you run the test projects individually, perhaps it fails for one and not the other.

**Comment by AsierVillanueva** [comment] 2021-02-09 15:25
@tonyhallett No. Same result with either one.

**Comment by draxtor** [comment] 2021-02-09 15:38
@tonyhallett  Unfortunately I cannot share the repo. 
1.1.63 works, thanks

My Setup:

- VS 2019 Professional 16.7.7
- 3 Library Projects  .Net Core 3.1
- 2 Background Worker Services  .Net Core 3.1
- 2 Asp.Net Core 3.1 (one API and one gRPC) project

**Comment by tonyhallett** [comment] 2021-02-09 16:55
@AsierVillanueva @mmbatha @draxtor 

Please can you use https://ci.appveyor.com/api/buildjobs/98bguwyjn56i56dy/artifacts/FineCodeCoverage.vsix it will still have the exception but it should be logged this time.
Thanks for your assistance.

**Comment by AsierVillanueva** [comment] 2021-02-09 17:10
@tonyhallett 
Ok. This is the generated log:

```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Error processing unit test events
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Engine.Model.CoverageProject.<SetAssemblyNameAndReferencedProjectsAsync>d__67.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<PrepareForCoverageAsync>d__66.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<PrepareCoverageProjectsAsync>d__40.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass42_0.<<ReloadCoverage>b__0>d.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 251
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Engine.Model.CoverageProject.<SetAssemblyNameAndReferencedProjectsAsync>d__67.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<PrepareForCoverageAsync>d__66.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<PrepareCoverageProjectsAsync>d__40.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass42_0.<<ReloadCoverage>b__0>d.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 251<---
```

**Comment by tonyhallett** [comment] 2021-02-09 17:28
@AsierVillanueva 
Thanks.  If you could run it again with https://ci.appveyor.com/api/buildjobs/x6sq0ciqbad34b1h/artifacts/FineCodeCoverage.vsix I have added some more logging.  It should enable a resolution.

**Comment by AsierVillanueva** [comment] 2021-02-09 18:16
@tonyhallett 
This is the log:

```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : ProjectFile D:\Repos\ProjectFolder\Tests\ProductName.Services.Tests\ProductName.Services.Tests.csproj

Fine Code Coverage : Projects in solution:

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Model\ProductName.Model.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Services\ProductName.Services.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.WebApi\ProductName.WebApi.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Core\ProductName.Core.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Client\ProductName.Client.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Data.Sql\ProductName.SqlServer.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Data\ProductName.Data.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Data.MySql\ProductName.MySql.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Api.Model\ProductName.Api.Model.csproj

Fine Code Coverage : Error processing unit test events
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Engine.Model.CoverageProject.<SetAssemblyNameAndReferencedProjectsAsync>d__67.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<PrepareForCoverageAsync>d__66.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<PrepareCoverageProjectsAsync>d__40.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass42_0.<<ReloadCoverage>b__0>d.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 251
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Engine.Model.CoverageProject.<SetAssemblyNameAndReferencedProjectsAsync>d__67.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<PrepareForCoverageAsync>d__66.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<PrepareCoverageProjectsAsync>d__40.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass42_0.<<ReloadCoverage>b__0>d.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 251<---
```

**Comment by tonyhallett** [comment] 2021-02-09 18:38
@AsierVillanueva 
Many thanks.  Below is the code that throws.  It is throwing because your test project is not in the solution.  Why is it not in the solution ?

```
logger.Log("ProjectFile " + ProjectFile);
logger.Log("Projects in solution:");
var project = dte.Solution.Projects.Cast<Project>().First(p =>
{
	var projectFullName = "";
	try
	{
	  projectFullName = p.FullName;
	  logger.Log(projectFullName);
	}
	catch { }
	  return projectFullName == ProjectFile;
	});
```

**Comment by AsierVillanueva** [comment] 2021-02-09 18:46
@tonyhallett The test project is in the solution but not in the root folder. Is in a "Tests" subfolder.

This is the projects definition in the sln file:


```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.29728.190
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Model", "ProductName.Model\ProductName.Model.csproj", "{7C1DCDC7-74FF-48EA-A2F1-BD402F86831E}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Services", "ProductName.Services\ProductName.Services.csproj", "{B720E7B9-2EBC-4D6E-B16A-9937AB397B18}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.WebApi", "ProductName.WebApi\ProductName.WebApi.csproj", "{F723C338-D923-479B-9563-699C5A4903C3}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Core", "ProductName.Core\ProductName.Core.csproj", "{1457C776-D0E1-4069-9C82-F8BD4A7BA34B}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Client", "ProductName.Client\ProductName.Client.csproj", "{9AB89408-494E-419B-ABBD-3C664B1F864B}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.SqlServer", "ProductName.Data.Sql\ProductName.SqlServer.csproj", "{DAD37483-39D3-4182-B86D-47911B4E4AEC}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Data", "ProductName.Data\ProductName.Data.csproj", "{D820298B-F2E8-4472-A9C4-4967062B1C34}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.MySql", "ProductName.Data.MySql\ProductName.MySql.csproj", "{2F1C37E6-1997-405A-9DD8-A8BA2C40FF9E}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Api.Model", "ProductName.Api.Model\ProductName.Api.Model.csproj", "{32C55BAC-710C-4509-952E-BA53210CB858}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{11026F9B-E825-4408-B956-81B85C385EDC}"
	ProjectSection(SolutionItems) = preProject
		Version.info = Version.info
	EndProjectSection
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Tests", "Tests", "{644E9682-1559-40A0-8EF8-E477E8704C92}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "ProductName.TestNewman", "ProductName.TestNewman", "{4EEEDFCF-9AEF-4419-AC6B-E3010AB01AD9}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Test.Newman", "Tests\ProductName.Test.Newman\ProductName.Test.Newman.csproj", "{5E7E8D98-1693-439E-92A6-5B1DAE2BFF4B}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ProductName.Services.Tests", "Tests\ProductName.Services.Tests\ProductName.Services.Tests.csproj", "{4E99086E-2805-4644-B03D-FB7231AEEE39}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ProductName.WebApi.Tests", "Tests\ProductName.WebApi.Tests\ProductName.WebApi.Tests.csproj", "{26567882-15D0-49AC-B8BC-6A2AFA4B242A}"
EndProject

```

There are two test projects:

Tests\ProductName.Services.Tests\ProductName.Services.Tests.csproj
Tests\ProductName.WebApi.Tests\ProductName.WebApi.Tests.csproj

**Comment by tonyhallett** [comment] 2021-02-09 19:04
@AsierVillanueva 
I cannot see why dte.Solution.Projects does not include the test project.  Any thoughts ?

**Comment by tonyhallett** [comment] 2021-02-09 19:20
@FortuneN I will put back the old code if I cannot get to the bottom of this although will then need a solution for https://github.com/FortuneN/FineCodeCoverage/issues/73.  A design time build would be necessary.

**Comment by tonyhallett** [comment] 2021-02-10 00:21
@AsierVillanueva @mmbatha @draxtor

Please can you try https://ci.appveyor.com/api/buildjobs/x6sq0ciqbad34b1h/artifacts/FineCodeCoverage.vsix it should fallback to the old code when the issue encountered by @AsierVillanueva occurs.

Again thanks for your help and patience.

**Comment by AsierVillanueva** [comment] 2021-02-10 07:05
The error remains:

```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : ProjectFile D:\Repos\ProjectFolder\Tests\ProductName.Services.Tests\ProductName.Services.Tests.csproj

Fine Code Coverage : Projects in solution:

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Model\ProductName.Model.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Services\ProductName.Services.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.WebApi\ProductName.WebApi.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Core\ProductName.Core.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Client\ProductName.Client.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Data.Sql\ProductName.SqlServer.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Data\ProductName.Data.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Data.MySql\ProductName.MySql.csproj

Fine Code Coverage : D:\Repos\ProjectFolder\ProductName.Api.Model\ProductName.Api.Model.csproj

Fine Code Coverage : Error processing unit test events
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Engine.Model.CoverageProject.<SetAssemblyNameAndReferencedProjectsAsync>d__67.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<PrepareForCoverageAsync>d__66.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<PrepareCoverageProjectsAsync>d__40.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass42_0.<<ReloadCoverage>b__0>d.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 251
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Engine.Model.CoverageProject.<SetAssemblyNameAndReferencedProjectsAsync>d__67.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.Model.CoverageProject.<PrepareForCoverageAsync>d__66.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<PrepareCoverageProjectsAsync>d__40.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FineCodeCoverage.Engine.FCCEngine.<>c__DisplayClass42_0.<<ReloadCoverage>b__0>d.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 251<---
```

**Comment by tonyhallett** [comment] 2021-02-10 09:29
@AsierVillanueva 
I did correct the code but bizarrely the vsix link was not up to date.
I have checked the code in the vsix below and it does contain the necessary correction.  If you could try once again please.
https://ci.appveyor.com/api/buildjobs/pw3jn6kl2i8bimms/artifacts/FineCodeCoverage.vsix

**Comment by AsierVillanueva** [comment] 2021-02-10 09:34
@tonyhallett Yes. This one works.

**Comment by tonyhallett** [comment] 2021-02-10 10:12
@FortuneN Please can you publish to the marketplace

**Comment by FortuneN** [comment] 2021-02-10 10:27
Done

**Comment by tonyhallett** [comment] 2021-02-10 11:15
@AsierVillanueva
Thanks for your assistance.

Fixed by https://github.com/FortuneN/FineCodeCoverage/commit/f2a98205bc4a355bef122757bfe6f8f64c3eda6d

**Closed by tonyhallett** 2021-02-10 11:15 UTC
