### ISSUE TITLE
Not showing coverage on all projects on big codebase (NUnit v3)

### ISSUE THREAD

**Issue by rmed1na** [FortuneN/FineCodeCoverage#33] opened 2020-12-03 02:22 UTC
### Installed product versions
- Visual Studio: 2019 Community
- This extension: latest

### Description
Code coverage is not shown on reports neither on the green/red bar lines on the margin on lots of projects from a big codebase (50 projs).

Only covers some projs, around 1/3

### Steps to recreate
1. Have a big codebase (or just copy the same proj multiple times)
2. Have some test for all the projs 
3. Run the tests
4. Check code coverage (margin lines & reports)

### Current behavior
Not showing coverage for all the assemblies (none excluded)

### Expected behavior
Should consider code coverage from all the assemblies

### Side Notes
Also, I'm using NUnit 3, if it helps to know
Btw, great product!

**Comment by FortuneN** [comment] 2020-12-03 14:10
Please post the log

**Comment by rmed1na** [comment] 2020-12-03 20:27
[fine-code-coverage output log.txt](https://github.com/FortuneN/FineCodeCoverage/files/5638761/fine-code-coverage.output.log.txt)

Seems like it's only getting the NUnit VS Adapter 2.2.0.0 tests
I have a lot with v3

**Comment by FortuneN** [comment] 2020-12-03 23:25
I understand that you may not want your log to be public; you could post the FULL log privately to my mailbox  (fortunengwenya@gmail.com)

Looking at the logs helps me understand what's going on.

**Comment by FortuneN** [comment] 2020-12-04 00:40
Also, please post a repro with 
- At least one NUnit VS Adapter V2
- At least one NUnit VS Adapter V3

**Comment by rmed1na** [comment] 2020-12-04 05:15
Sure, just sent the email :)

**Comment by FortuneN** [comment] 2020-12-04 06:29
Please post a repro with
At least one NUnit VS Adapter V2
At least one NUnit VS Adapter V3

**Comment by FortuneN** [comment] 2020-12-10 16:41
Repro, please

**Comment by rmed1na** [comment] 2020-12-25 00:44
Hello,

Happy holidays. Sorry for the very late response. Have been some busy days. I’m attaching two files:

1. Fine-code-coverage.output > log generated when ran all the unit tests on my project (2k+, some v3, some v2).
2. Fine-code-coverage.output-v2 > log generated when ran 57 v2 unit tests.

I see it says there’re no unit tests on the bin folder, but it is there. I also made a new proj from scratch and added some v2 and v3 unit tests from separate controllers but on that project it did work fine for all files. Must be something on my big project.

Thanks for the help,
Best regards
Rolando

**Comment by bbadjari** [comment] 2021-02-16 19:12
I'm having a similar issue in that code coverage is reported using the 'NUnit VS Adapter V3' plugin with the Enterprise Edition of Visual Studio (and not your plugin since it isn't needed), but does not work when using your plugin with the Community Edition.

I have an [open source project](https://github.com/bbadjari/vsfile) available if you would like to attempt this yourselves.

**Comment by tonyhallett** [comment] 2021-02-25 16:48
@bbadjari 
This is the relevant output running against your test project 

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (VSFile.Tests)

Fine Code Coverage : OpenCover Run (VSFile.Tests) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path32 
 "-target:C:\Users\tonyh\AppData\Local\FineCodeCoverage\msTestPlatform\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" 
 "-excludebyfile:**/Migrations/*" 
 "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" 
 "-targetargs:\"C:\Users\tonyh\Source\Repos\vsfile\VSFile.Tests\bin\Debug\fine-code-coverage\build-output\VSFile.Tests.dll\" " 
 "-output:C:\Users\tonyh\Source\Repos\vsfile\VSFile.Tests\bin\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"

Fine Code Coverage : OpenCover Run (VSFile.Tests)
Executing: C:\Users\tonyh\AppData\Local\FineCodeCoverage\msTestPlatform\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
No test is available in C:\Users\tonyh\Source\Repos\vsfile\VSFile.Tests\bin\Debug\fine-code-coverage\build-output\VSFile.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.

------------
if you [install the nuget package](https://docs.nunit.org/articles/vs-test-adapter/Adapter-Installation.html#installing-the-nuget-package) then FCC will work.  ( I personally think it is a better idea to use the nuget )

FCC could read your project file for the presence of a known test adapter and if absent use a visual studio api to look at your installed extensions and find the /TestAdapterPath......
If you would like to attempt it then we would certainly look at your pull request !

In the mean time I will add to the readme that is expected that nunit etc has been added as a nuget package.

--------

@rmed1na Is this the cause of your isse as well ?

**Comment by tonyhallett** [comment] 2021-02-25 17:16
Perhaps FCC can use "/usevsixextensions:true" https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0004-Adapter-Extensibility.md

**Comment by rmed1na** [comment] 2021-02-25 17:49
In my case, I already had the NUnit package installed before FCC

**Comment by tonyhallett** [comment] 2021-02-25 17:51
@rmed1na Are you saying that you do not have the test adapter visual studio extension ?

**Comment by rmed1na** [comment] 2021-02-25 17:57
I do have it
![image](https://user-images.githubusercontent.com/30838319/109195770-ed82ab80-7768-11eb-92f6-2d4590809ae9.png)

**Comment by tonyhallett** [comment] 2021-02-25 17:59
@rmed1na For the solution that you were having issues with, do you have the nuget test adapter in your test projects ?

**Comment by rmed1na** [comment] 2021-02-26 22:49
Well I was missing the nuget on one of the projects. Seems like it's already showing up coverage on some files it didn't previously.

Will keep testing. Thanks

**Comment by tonyhallett** [comment] 2021-03-01 14:23
@rmed1na Closing this issue as I believe the issue has been identified and addressed.

**Closed by tonyhallett** 2021-03-01 14:23 UTC
Labels: NUnit Extension, repro, waiting for feedback
