### ISSUE TITLE
Getting ('""' is not recognized as an internal or external command) when running tests

### ISSUE THREAD

**Issue by alexandruf** [FortuneN/FineCodeCoverage#60] opened 2021-01-07 11:06 UTC
### Installed product versions
- Visual Studio: 2019 16.8.1
- This extension: 1.1.52
- .NET version: 5

### Description
I have a medium size .sln with

Project.DataAccess.csproj
Project.Repository.csproj
Project.Services.csproj
Project.Main.csproj
Project.Test.csproj

The test project uses Nunit.Framework.
When tests are run, FineCodeCoverage kicks in and the output is (no changes to default configuration made):

========== Build: 0 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (Project.Test)

Fine Code Coverage : Coverlet Run (Project.Test) Arguments 
"D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\Project.Test.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage\project.coverage.xml"
--targetargs "test  ""D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\Project.Test.dll"" --nologo --blame  --results-directory ""D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage"" --diag ""D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (Project.Test)
D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0>"" "D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\Project.Test.dll" --format "cobertura" --exclude-by-file "**/Migrations/*" --exclude-by-attribute "GeneratedCode" --target "dotnet" --threshold-type line --threshold-stat total --threshold 0 --output "D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage\project.coverage.xml" --targetargs "test  ""D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\Project.Test.dll"" --nologo --blame  --results-directory ""D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage"" --diag ""D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage/diagnostics.log""  "  1>"D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\17f86250.bat.output" 

'""' is not recognized as an internal or external command,
operable program or batch file.

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage"
"-reports:D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage\project.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : Error
System.Exception: D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage>"" "-targetdir:D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage" "-reports:D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage\project.coverage.xml" "-reporttypes:Cobertura"  1>"D:\_WORK_CDT_EXP\Project\Project.Test\bin\Debug\net5.0\fine-code-coverage\63969f44.bat.output" 

'""' is not recognized as an internal or external command,
operable program or batch file.
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<RunReportGenerator>g__run|22_1(String outputReportType, String inputReports, <>c__DisplayClass22_0& ) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 215
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.RunReportGenerator(IEnumerable`1 coverOutputFiles, Boolean darkMode, String& unifiedHtmlFile, String& unifiedXmlFile, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 226
   at FineCodeCoverage.Engine.FCCEngine.ReloadCoverage(IEnumerable`1 projects, Boolean darkMode) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 456
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass25_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 193

Fine Code Coverage : ================================== ERROR ==================================

Is something wrong in my configuration?

**Comment by t-johnson** [comment] 2021-01-12 15:42
I'm also struggling to get this extension to work.  I'm seeing the same error as this.

I've also noticed that I get 'Cannot find CodeCoverage.exe' in the build log.  I resolved this by fixing the path:
`C:\Users\xxxxxxx\AppData\Local\FineCodeCoverage\msTestPlatform\tools\net451\Team Tools\Dynamic%20Code%20Coverage%20Tools`

to replace the %20 with space:

`C:\Users\xxxxxxx\AppData\Local\FineCodeCoverage\msTestPlatform\tools\net451\Team Tools\Dynamic Code Coverage Tools`

and now at least the command line that is generated by this addin works in the OpenCover Prompt outside of VS...

**Comment by t-johnson** [comment] 2021-01-12 16:08
It seems flip between the "" empty command and and error about the output folder not existing...

**Comment by t-johnson** [comment] 2021-01-12 17:30
I believe this to be caused by the code quickly deleting and re-creating the temporary folder.  my machine has CarbonBlack installed, and this product is known to block such rapid changes to files/folders.
Modifying the code for this extension to simply delete for files in the folder if it exists seems to make it work for me.

**Comment by FortuneN** [comment] 2021-01-13 13:17
@t-johnson thank you
@alexandruf Please try latest update

**Comment by tonyhallett** [comment] 2021-02-13 14:03
@alexandruf 
I think that the initialization process did not work and that coverlet was not installed.  I have changed the code so that initialization is logged.

Please can you follow these steps so I can investigate further.
a) Delete the FineCodeCoverage app data folder ( for me it is C:\Users\tonyh\AppData\Local\FineCodeCoverage )
b) Install this version of [fine code coverage ](https://ci.appveyor.com/api/buildjobs/y2uqs10127x0ginv/artifacts/FineCodeCoverage.vsix)
c) Open vs and check the output window pane - FCC.  You should see Initializing / install info / Initialized if successful or an error message.
![image](https://user-images.githubusercontent.com/11292998/107851715-d60c0000-6e03-11eb-8e7d-ca0ce43c42c9.png)
d) If no error message run a test and should work.  ( If there is an error you could run a test and FCC should repeat the initialization error )

**Comment by tonyhallett** [comment] 2021-02-13 17:06
Please use [this version](https://ci.appveyor.com/api/buildjobs/j47e6nqtstrjxaqv/artifacts/FineCodeCoverage.vsix) instead

**Comment by tonyhallett** [comment] 2021-02-15 11:42
Fixed by https://github.com/FortuneN/FineCodeCoverage/commit/75389cfffe94a985c71f5f176c326174897470b9

**Closed by tonyhallett** 2021-02-15 11:42 UTC
Labels: resolved upon publish
