### ISSUE TITLE
Code coverage for async methods

### ISSUE THREAD

**Issue by LoriBru** [FortuneN/FineCodeCoverage#116] opened 2021-03-19 11:13 UTC
- Visual Studio: 2019 Community
- This extension: 1.1.131

I have issues obtaining code coverage for async methods. This makes me wonder if they are supported/tested in the first place.
I am using MSTest to test async methods, and despite the test is executed successfully, I never get the code coverage for the tested methods.
I tried both to write an "async Task" type test method and a normal "void" test method but none of them are working.

![1](https://user-images.githubusercontent.com/22811725/111771739-5793f980-88ac-11eb-865a-78e4be83bd6b.png)
![2](https://user-images.githubusercontent.com/22811725/111771748-59f65380-88ac-11eb-9cf4-a098dd7bf52c.png)

**Comment by tonyhallett** [comment] 2021-03-19 12:03
Please can you post the results from the FCC output window pane

**Comment by LoriBru** [comment] 2021-03-19 14:33
So should async method work without issues?
Yes sure, here it is. Thanks for the support.

`Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (Core.Devices.MicroscopeTests)

Fine Code Coverage : OpenCover Run (Core.Devices.MicroscopeTests) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path64 
 "-target:C:\Users\loribru\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" 
 "-excludebyfile:**/Migrations/*" 
 "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" 
 "-targetargs:\"C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\build-output\Core.Devices.MicroscopeTests.dll\" " 
 "-output:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"

Fine Code Coverage : OpenCover Run (Core.Devices.MicroscopeTests)
Executing: C:\Users\loribru\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Passed ToBitmapImage_NetVipsImage_NotNull [639 ms]
  Passed ToBitmapImage_Bitmap_NotNull [26 ms]
  Passed ToBitmapImage_ByteArray_NotNull [12 ms]
  Passed Connect_False_ReturnFalse [1 m]
  Passed Connect_True_ReturnFalse [11 ms]
  Passed Disconnect [3 ms]
  Passed StartAcquisitionFromProtocol_AcquisitionParameters [4 s]
  Passed AutofocusMap_ReturnFalse [451 ms]
  Passed AutofocusTile_ReturnFalse [30 ms]

Test Run Successful.
Total tests: 9
     Passed: 9
 Total time: 1,1661 Minutes
Committing...
Visited Classes 15 of 177 (8.47)
Visited Methods 48 of 1494 (3.21)
Visited Points 217 of 9434 (2.30)
Visited Branches 61 of 4265 (1.43)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 15 of 178 (8.43)
Alternative Visited Methods 48 of 1705 (2.82)

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-03-19T15:26:45: Arguments
2021-03-19T15:26:45:  -targetdir:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output
2021-03-19T15:26:45:  -reports:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\project.coverage.xml
2021-03-19T15:26:45:  -reporttypes:Cobertura
2021-03-19T15:26:46: Writing report file 'C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-03-19T15:26:46: Report generation took 0,5 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:C:\USERS\loribru\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D0C6A0E1\EXTENSIONS\SDKVCRDN.DIA\ReportGeneratorPlugins.dll"
"-reporttypes:FccDark"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-03-19T15:26:46: Arguments
2021-03-19T15:26:46:  -targetdir:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output
2021-03-19T15:26:46:  -reports:C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-03-19T15:26:46:  -plugins:C:\USERS\loribru\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D0C6A0E1\EXTENSIONS\SDKVCRDN.DIA\ReportGeneratorPlugins.dll
2021-03-19T15:26:46:  -reporttypes:FccDark
2021-03-19T15:26:47: Writing report file 'C:\Users\loribru\Source\Workspaces\Core\Core.Devices.MicroscopeTests\bin\x64\Debug\fine-code-coverage\coverage-tool-output\index.html'
2021-03-19T15:26:47: Report generation took 0,4 seconds

Fine Code Coverage : ================================== DONE ==================================`

**Comment by tonyhallett** [comment] 2021-03-19 16:28
There is an open issue on open cover regarding async methods - could be related
https://github.com/OpenCover/opencover/issues/657

Does your coverage report agree with the gutter highlighting ?

**Comment by LoriBru** [comment] 2021-03-22 07:35
Thank you for linking this issue. It looks like there is a problem with async methods indeed. That's pretty bad.
Yes, the report agrees with the missing coverage highlighting.

**Comment by tonyhallett** [comment] 2021-03-22 08:37
Is your project open source ?

**Comment by tonyhallett** [comment] 2021-03-22 09:29
Can you try a previous version of FCC
https://ci.appveyor.com/api/buildjobs/qyttaad09mdg3ral/artifacts/FineCodeCoverage.vsix

Please delete the contents of AppData\Local\FineCodeCoverage beforehand

**Comment by LoriBru** [comment] 2021-03-22 13:26
No it's not.
Yes I'll try this version and report the results, but I've been having the same problem for several weeks before opening this issue.
Also, I don't know if it's related or if it is normal, but after executing even a single small test, it really takes a long time before producing the report in FCC (several minutes).

**Comment by LoriBru** [comment] 2021-03-22 13:40
I confirm: same behavior with the provided extension version.

**Comment by tonyhallett** [comment] 2021-03-22 13:40
If you run a single test FCC will run all the tests to get coverage.

**Comment by tonyhallett** [comment] 2021-03-22 13:42
Can you post the files project.coverage.xml and Cobertura.xml
Test\bin\Debug\fine-code-coverage\coverage-tool-output

If you can change your project to SDK style then coverage will go through coverlet instead of opencover and you may get better results that way.

**Comment by LoriBru** [comment] 2021-03-22 13:53
I had a quick look at those files and it looks like they disclose too much about the project architecture. I am not sure I can share that, I need to check.

Sorry but I do not get your last sugggestion. How do I switch to SDK style? What does it mean?

**Comment by tonyhallett** [comment] 2021-03-22 14:01
There are two formats for the .csproj file.  The newer style is called SDK style and is the format you get for .NET core projects.
When you create a .NET Framework project you will get the old style but you can use the new style.

https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview
https://stackoverflow.com/questions/63055430/how-to-create-a-sdk-style-net-framework-project-in-vs

**Comment by LoriBru** [comment] 2021-03-22 15:33
I thought that it was only possible to have that with .NET Core projects.
Now that I think about it I should have a version of the same project ported to .NET Core. I will test the coverage there to see if it behaves differently.

**Comment by LoriBru** [comment] 2021-03-23 07:34
It does work correctly on .NET 5 indeed! I get the right coverage, both in the report and the highlighting.

**Comment by tonyhallett** [comment] 2021-03-24 12:28
Are you happy to close this issue ?

**Comment by LoriBru** [comment] 2021-03-25 07:42
Well, for .NET Framework the issue is still there, so I would keep it open, what do you think?

**Comment by tonyhallett** [comment] 2021-03-25 08:44
I would like to be able to determine if it is an issue with FCC or one with OpenCover. If it is OpenCover then it should be closed. 

Can you post the files that I asked for ?
Also what version of .Net Framework is being used by projects ? What version of .Net Framework is installed on your machine ?

**Comment by tonyhallett** [comment] 2021-03-25 08:45
You could run your coverage outside of FCC directly with OpenCover and compare results.

**Comment by LoriBru** [comment] 2021-03-29 15:28
Unfortunately, I cannot post them.
The application runs on 4.7.2 but I also have 4.8 installed on my machine.
I am available to perform other tests to investigate the issue but I would need detailed instructions.

**Comment by tonyhallett** [comment] 2021-03-29 19:33
Can you run directly with OpenCover using the arguments generated by FCC, as seen in the output window pane, and compare. If the results are the same then the issue is for OpenCover and not here.

**Comment by tonyhallett** [comment] 2021-03-29 19:37
OpenCover can be found in the fine code coverage folder in app data.

**Comment by tonyhallett** [comment] 2021-05-15 08:19
@LoriBru 
Are you able to create a minimal reproducable example that I can debug ?

**Comment by tonyhallett** [comment] 2021-05-17 21:30
@LoriBru 

> I am available to perform other tests to investigate the issue but I would need detailed instructions.

We need to determine the nature of this issue.  If you cannot assist I will close this issue.

**Comment by joshuanj** [comment] 2021-06-22 00:31
I ran into a similar issue. In my case, I was able to trace it to an uncaught exception, thrown within an async void. 

`        
protected virtual async void onViewModelChanged(object sender, PropertyChangedEventArgs args)
        {
await InvokeAsync(() => StateHasChanged());
        }

`

In the snippet above, the InvokeAsync() method is suppose to execute the StateHasChanged() from the UI thread; but while under test there is no rendering service available. So it always throws an exception while under unit testing. The result of StateHasChanged() isn't relevant in the unit tests and the exception isn't caught; but it does seem to result in 0% test coverage for the entire solution. 

The unit tests is fulfilling it's purpose. So as a work around, I've just excluded this method from FCC, and run the associated unit tests manually as needed.

**Comment by tonyhallett** [comment] 2021-06-22 07:21
@joshuanj Thanks for reporting this.  My expectation is that this is not an issue with FCC but the underlying coverage tools.
Can I ask you tto include the method and post the results of the FCC pane in the Visual Studio output window.
I am interested in whether changing to SDK style project will benefit you as it did for @LoriBru 
and if you are already using SDK style whether a switch to coverlet collector changes the coverage.

**Comment by joshuanj** [comment] 2021-06-22 18:11
@tonyhallett Yes, that seems reasonable. Here's a demo that can reproduce the issue: 
https://github.com/joshuanj/UnitTestCoverageToolErrorDemo

Calling this method from a test results in no coverage.

```
public async void SimulateExceptionInAsyncTask_FromAsyncVoid()
{
    await Task.Run(() => 
    {
        throw new Exception();
    });
}
```


FFC Output
```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (UnitTestCoverageToolErrorDemo)

Fine Code Coverage : Coverlet Run (UnitTestCoverageToolErrorDemo) Arguments 
"C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\build-output\UnitTestCoverageToolErrorDemo.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--exclude-by-attribute "ExcludeFromFineCodeCoverageAttribute"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\UnitTestCoverageToolErrorDemo.coverage.xml"
--targetargs "test  ""C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\build-output\UnitTestCoverageToolErrorDemo.dll"" --nologo --blame  --results-directory ""C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"" --diag ""C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (UnitTestCoverageToolErrorDemo)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
**The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.**
   at UnitTestCoverageToolErrorDemo.DemoObject.<>c.<SimulateExceptionInAsyncTask_FromAsyncVoid>b__3_0() in C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\DemoObject.cs:line 31
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UnitTestCoverageToolErrorDemo.DemoObject.SimulateExceptionInAsyncTask_FromAsyncVoid() in C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\DemoObject.cs:line 29
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Test Run Aborted.

Calculating coverage result...
  Generating report 'C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\UnitTestCoverageToolErrorDemo.coverage.xml'
+-------------------------------+------+--------+--------+
| Module                        | Line | Branch | Method |
+-------------------------------+------+--------+--------+
| UnitTestCoverageToolErrorDemo | 0%   | 100%   | 0%     |
+-------------------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 100%   | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 100%   | 0%     |
+---------+------+--------+--------+

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\UnitTestCoverageToolErrorDemo.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-06-22T11:08:09: Arguments
2021-06-22T11:08:09:  -targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output
2021-06-22T11:08:09:  -reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\UnitTestCoverageToolErrorDemo.coverage.xml
2021-06-22T11:08:09:  -reporttypes:Cobertura
2021-06-22T11:08:09: Writing report file 'C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-06-22T11:08:09: Report generation took 0.1 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:c:\users\josh\appdata\local\microsoft\visualstudio\16.0_d58ae1d8\extensions\ybesfeb4.lo4\ReportGeneratorPlugins.dll"
"-reporttypes:FccDark"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-06-22T11:08:09: Arguments
2021-06-22T11:08:09:  -targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output
2021-06-22T11:08:09:  -reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-06-22T11:08:09:  -plugins:c:\users\josh\appdata\local\microsoft\visualstudio\16.0_d58ae1d8\extensions\ybesfeb4.lo4\ReportGeneratorPlugins.dll
2021-06-22T11:08:09:  -reporttypes:FccDark
2021-06-22T11:08:09: Writing report file 'C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\index.html'
2021-06-22T11:08:10: Report generation took 0.3 seconds

Fine Code Coverage : ================================== DONE ==================================

```

**Comment by tonyhallett** [comment] 2021-06-23 07:27
@joshuanj Can you try the coverlet collector approach ?

**Comment by joshuanj** [comment] 2021-06-23 18:34
@tonyhallett Sure, I'm seeing the same result with coverlet collector.

FCC Output
```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (UnitTestCoverageToolErrorDemo)

Fine Code Coverage : Coverlet Collector Run (UnitTestCoverageToolErrorDemo) Arguments 
"C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\build-output\UnitTestCoverageToolErrorDemo.dll" --blame --nologo --diag "C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output/diagnostics.log" --settings "C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output/FCC.runsettings" --results-directory "C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"

Fine Code Coverage : Coverlet Collector Run (UnitTestCoverageToolErrorDemo)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.


Attachments:
  C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\f46328de-e658-4674-a39c-cf83edf91610\coverage.cobertura.xml

The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at UnitTestCoverageToolErrorDemo.DemoObject.<>c.<SimulateExceptionInAsyncTask_FromAsyncVoid>b__3_0() in C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\DemoObject.cs:line 31
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UnitTestCoverageToolErrorDemo.DemoObject.SimulateExceptionInAsyncTask_FromAsyncVoid() in C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\DemoObject.cs:line 29
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Test Run Aborted.

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\UnitTestCoverageToolErrorDemo.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-06-23T11:11:13: Arguments
2021-06-23T11:11:13:  -targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output
2021-06-23T11:11:13:  -reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\UnitTestCoverageToolErrorDemo.coverage.xml
2021-06-23T11:11:13:  -reporttypes:Cobertura
2021-06-23T11:11:14: Writing report file 'C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-06-23T11:11:14: Report generation took 0.1 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:C:\USERS\JOSH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D58AE1D8\EXTENSIONS\YBESFEB4.LO4\ReportGeneratorPlugins.dll"
"-reporttypes:FccDark"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-06-23T11:11:14: Arguments
2021-06-23T11:11:14:  -targetdir:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output
2021-06-23T11:11:14:  -reports:C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-06-23T11:11:14:  -plugins:C:\USERS\JOSH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D58AE1D8\EXTENSIONS\YBESFEB4.LO4\ReportGeneratorPlugins.dll
2021-06-23T11:11:14:  -reporttypes:FccDark
2021-06-23T11:11:14: Writing report file 'C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\index.html'
2021-06-23T11:11:14: Report generation took 0.3 seconds

Fine Code Coverage : ================================== DONE ==================================

```

Ultimately, I think you're right that the issue is part of the underlying coverage tools. While there isn't anything the FCC plugin can do to prevent the issue, it might be really helpful to visually indicate when the code coverage test runs are aborted. Perhaps something like:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at UnitTestCoverageToolErrorDemo.DemoObject.<>c.<SimulateExceptionInAsyncTask_FromAsyncVoid>b__3_0() in C:\Users\josh\source\repos\UnitTestCoverageToolErrorDemo\UnitTestCoverageToolErrorDemo\DemoObject.cs:line 31
```

In any case, thanks for your work creating this tool. I definitely owe you coffee.

**Comment by tonyhallett** [comment] 2021-11-14 15:03
@LoriBru 
Closing as I doubt this is FCC related.  There have been no other reports of similar issues.
If you can provide a minimal reproducible then I will reopen and look at it.

**Closed by tonyhallett** 2021-11-14 15:03 UTC
Labels: waiting for feedback
