### ISSUE TITLE
Lines without code marked as uncovered

### ISSUE THREAD

**Issue by jfelipearaujo** [FortuneN/FineCodeCoverage#131] opened 2021-04-24 19:36 UTC
### Installed product versions
- Microsoft Visual Studio Community 2019 Version 16.8.5
- This extension: 1.1.141

### Description
Code coverage show a line as uncovered, but this line does not have code.

### Steps to recreate
1. Run tests
2. Wait until the coverage report appear
3. Some files have lines marked as uncovered

### Current behavior
Some lines without code are marked as uncovered.

### Expected behavior
Lines without code maybe not be considered in the report coverage.

### Examples:

![error_example_1](https://user-images.githubusercontent.com/7776944/115970754-df5bcc00-a51a-11eb-9843-1f688dc5f78f.png)

![error_example_2](https://user-images.githubusercontent.com/7776944/115970769-02867b80-a51b-11eb-8aa9-e1ef2cb8da6e.png)

**Comment by tonyhallett** [comment] 2021-04-24 21:06
Please can you provide a minimal reproducable example, a github repo that I can look at.

It looks like for the first example you could be throwing an exception and the function is not exited ?

**Comment by jfelipearaujo** [comment] 2021-04-24 21:16
@tonyhallett I gave you access to my personal project. There you can find some examples to reproduce the error.

**Comment by tonyhallett** [comment] 2021-04-24 21:50
ShouldValidateWithErrorWhenLastNameIsInvalid

This test method fails the assertion and throws an exception and as such the method never exits and the closing brace is red.
`errorMessages.Should().Contain(errorMessage);`

This is the case for most of the methods in this test class and I suspect that this is the behaviour in the other test classes too.

If you look at the tests that do pass they have a green closing brace.
![image](https://user-images.githubusercontent.com/11292998/115973735-3da2a200-a54f-11eb-94fd-60bb57398761.png)

![image](https://user-images.githubusercontent.com/11292998/115973746-4d21eb00-a54f-11eb-9d6c-a5f3ea1b310b.png)

**Comment by jfelipearaujo** [comment] 2021-04-24 21:54
@tonyhallett this is weird because here all the tests are passing. I’m using fluent validation and comparing the message generated by the API. Your computer is configured in English and my in Portuguese.

I will do some tests to see if the message language is the problem.

**Comment by tonyhallett** [comment] 2021-04-24 22:04
That would explain it on my machine !

**Comment by tonyhallett** [comment] 2021-04-24 22:27
Given that you are using the built in language behaviour you could change your tests to use https://docs.fluentvalidation.net/en/latest/testing.html
```
var person = new Person { Name = "Jeremy" };
var result = validator.TestValidate(person);

// Assert that there should be a failure for the Name property.
result.ShouldHaveValidationErrorFor(x => x.Name);

// Assert that there are no failures for the age property.
result.ShouldNotHaveValidationErrorFor(x => x.Age);

// You can also use a string name for properties that can't be easily represented with a lambda, eg:
result.ShouldHaveValidationErrorFor("Addresses[0].Line1");
```

Of course I would expect that given your tests pass then you should not be getting the red gutter mark.

**Comment by jfelipearaujo** [comment] 2021-04-24 22:53
@tonyhallett I don't know why but now no one of red gutter mark is showing.

Perhaps the other approach was wrong when checking whether the message was correct or not

See now the files have 100% of coverage:

![image](https://user-images.githubusercontent.com/7776944/115974855-3753fc00-a536-11eb-9bbb-3db36eae8448.png)

Thank you for your time and the tip about the fluent validation test extension.

**Closed** 2021-04-24 22:56 UTC
